[package]
name = "rust_port"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
nalgebra = { version = "0.32", features = ["serde-serialize"] }
serde_json = "1.0"

[build-dependencies]
cc = "1.0"
